# Generated by Django 3.0.8 on 2020-08-10 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_desc', models.CharField(max_length=500)),
                ('job_date', models.DateTimeField(verbose_name='job date')),
                ('job_min_bid', models.FloatField(default=0)),
                ('job_final_bid', models.FloatField(default=0)),
                ('job_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobbidder.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.FloatField()),
                ('bid_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobbidder.Company')),
                ('bid_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobbidder.Job')),
            ],
        ),
    ]
