# Generated by Django 3.0.8 on 2020-08-12 16:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobbidder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user_role', models.CharField(choices=[('C', 'CEO'), ('T', 'Trader'), ('B', 'Broker'), ('D', 'Data Analyst')], max_length=1)),
                ('user_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobbidder.Company')),
            ],
        ),
    ]
